image: Visual Studio 2022

environment:
  RESHARPER_GALLERY_KEY:
    secure: ZHMReQXlwdjhYK3JPKDy8zckH93IR0bvNW6vx1JrWtjciAPlbcttAhDJZhS0UV3DeJiG91Xk/ngBDflfJy3lXS8jGmCIiZ+EmkuWgrHwSeQ=
  MYGET_KEY:
    secure: 4p4wi7VlIH54Ue2IKX5E8FW30mZeHihIevL9l+nKol4w4UWRmIWbBhnGs1iflu4F

pull_requests:
  do_not_increment_build_number: true

build_script:
- ps: |
    (& cmd /c); [console]::OutputEncoding = New-Object System.Text.UTF8Encoding;
    & .\build.ps1 --target AppVeyor_Pipeline --resharper-gallery-key "$($Env:RESHARPER_GALLERY_KEY)" --myget-key "$($Env:MYGET_KEY)" --build-version git  --build-number $($Env:APPVEYOR_BUILD_NUMBER) --no-logo

test: off
deploy: off

artifacts:
  - path: 'artifacts\nugetPackages\*.nupkg'
  - path: 'artifacts\riderPackages\*.zip'
