######## RELEASE CONFIGURATION ########
-
  branches:
   only:
     - master
  
  version: 1.0.0.{build}
  configuration: Release
  platform: Any CPU

  before_build:
    - nuget restore

  build:
    project: AlexPovar.ResharperTweaks.sln
    verbosity: minimal
  
  after_build:
    - nuget pack AlexPovar.ResharperTweaks.nuspec -Version %APPVEYOR_BUILD_VERSION% -BasePath AlexPovar.ResharperTweaks\bin\Release
  
#  test:
#    assemblies:
#      - AlexPovar.ResharperTweaks.Tests.dll
  test: off

  artifacts:
    - path: '*.nupkg'
    
  assembly_info:
    patch: true
    file: AlexPovar.ResharperTweaks\Properties\AssemblyInfo.cs
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    
######## ANY_CONFIGURATION_BUILD ########
-
  version: 1.0.0.{build}
  configuration: Debug
  
  before_build:
    - nuget restore
    
  build:
    project: AlexPovar.ResharperTweaks.sln
    verbosity: minimal
    
  after_build:
    - nuget pack AlexPovar.ResharperTweaks.nuspec -Version %APPVEYOR_BUILD_VERSION% -BasePath AlexPovar.ResharperTweaks\bin\Debug
    
  test: off
  
  artifacts:
    - path: '*.nupkg'