######## RELEASE CONFIGURATION ########
-
  #Run builds for tags only
  branches:
    only:
      - master
      - /v\d(.\d)+/
      - /v\d(.\d)+-(\w)+/
  
  skip_non_tags: true
  
  configuration: Release
  platform: Any CPU
  
  environment:
    BUILD_VERSION: '0.0.0.0'
    SEMANTIC_BUILD_VERSION: $(BUILD_VERSION)
    IS_PRERELASE_BUILD: false
    
  image: Visual Studio 2017
  
  install:
    - ps: .\build\ResolveVersionFromNuSpec.ps1
    - ps: >
        Write-Host ">>>>>>>>> RUN RELEASE BUILD WITH DEPLOY <<<<<<<<<<<";
        
        $env:BUILD_VERSION = $env:BUILD_VERSION.Substring(0, $env:BUILD_VERSION.lastIndexOf('.'));
        
        $env:SEMANTIC_BUILD_VERSION = $env:BUILD_VERSION;
        
        $tagSuffix = [regex]::Match($env:APPVEYOR_REPO_TAG_NAME, "\d(.\d)+-(?<suffix>(\w)+)").Groups['suffix'].value
        
        if($tagSuffix) 
        { 
          $env:SEMANTIC_BUILD_VERSION = "$env:SEMANTIC_BUILD_VERSION-$tagSuffix"
          
          $env:IS_PRERELASE_BUILD = $true
        }
        
        
        
        Write-Host "BUILD VERSION: $env:BUILD_VERSION SEMANTIC VERSION: $env:SEMANTIC_BUILD_VERSION, PRE-RELEASE: $env:IS_PRERELASE_BUILD"
    
  before_build:
    - nuget restore

  build:
    project: AlexPovar.ReSharperHelpers.sln
    verbosity: minimal
  
  after_build:
    - nuget pack AlexPovar.ReSharperHelpers.nuspec -Version %SEMANTIC_BUILD_VERSION% -BasePath AlexPovar.ReSharperHelpers\bin\Release\net45
   
  test:
    assemblies:
      - AlexPovar.ReSharperHelpers.Tests.dll

  artifacts:
    - path: '*.nupkg'
    
  assembly_info:
    patch: true
    file: AlexPovar.ReSharperHelpers\Properties\AssemblyInfo.cs
    assembly_version: $(BUILD_VERSION)
    assembly_file_version: $(BUILD_VERSION)
    assembly_informational_version: $(BUILD_VERSION)
    
  deploy:
#    -
#      tag: $(APPVEYOR_REPO_TAG_NAME)
#      release: AlexPovar.ReSharperHelpers $(APPVEYOR_REPO_TAG_NAME)
#      description: >
#        ## Release notes:
#          - XXX
#      provider: GitHub
#      auth_token:
#        secure: OzVU+dQH6Xnhe6lBhEjUsJNTfKHQCT22+khHIBi2zRMelT+UzW1rCgGunZtAlBWP
#      artifact: /.*\.nupkg/
#      draft: true
#      prerelease: $(IS_PRERELASE_BUILD)
#      on:
#        appveyor_repo_tag: true         # deploy on tag push only

    -
      provider: NuGet
      server: https://resharper-plugins.jetbrains.com
      api_key:
        secure: n7O2pQ5KhsdnT2DhKmiU40gCt3Tl3/T/zxnclsYxgYwgxpNK2iZvK9apawWFMpCO
      skip_symbols: true
      artifact: /.*\.nupkg/
      on:
        appveyor_repo_tag: true

######## DEVELOP BUILD ########
- 
  branches:
    only:
      - develop
      
  skip_commits:
    files:
      - '*.md'

  configuration: Release
  platform: Any CPU
  
  environment:
    BUILD_VERSION: '0.0.0.0'
    SKIP_DEPLOY: false
    
  image: Visual Studio 2017
    
  install:
    - ps: .\build\ResolveVersionFromNuSpec.ps1
    - ps: >
        $env:SKIP_DEPLOY = [regex]::ismatch("$env:APPVEYOR_REPO_COMMIT_MESSAGE", "\[nodeploy\]")        
        
        Write-Host ">>>>>>>>> RUN DEVELOP BUILD. BUILD VERSION: $env:BUILD_VERSION SKIP DEPLOY: $env:SKIP_DEPLOY <<<<<<<<<<<"
        
  cache:
    - packages -> **\packages.config
    
  before_build:
    - nuget restore
    
  build:
    project: AlexPovar.ReSharperHelpers.sln
    verbosity: minimal
    
  after_build:
    - nuget pack AlexPovar.ReSharperHelpers.nuspec -Version %BUILD_VERSION% -BasePath AlexPovar.ReSharperHelpers\bin\Release\net45
    
  test: off
  
  artifacts:
    - path: '*.nupkg'
      name: LATEST package
      
  assembly_info:
    patch: true
    file: AlexPovar.ReSharperHelpers\Properties\AssemblyInfo.cs
    assembly_version: $(BUILD_VERSION)
    assembly_file_version: $(BUILD_VERSION)
    assembly_informational_version: $(BUILD_VERSION)
    
  deploy:
    -
      provider: NuGet
      server: https://www.myget.org/F/alexpovar-resharperhelpers-prerelease/api/v2/package
      api_key:
        secure: lbUAU6S3paEy82ZkEL0prxDANjgz/LFCyXeyCKaFQ00vvD3nENf5an+nTvDakFlL
      skip_symbols: true
      artifact: /.*\.nupkg/
      on:
        SKIP_DEPLOY: false