version: '1.0.0.{build}'
configuration: Release
#I should build AnyCPU instead of x86. Otherwise, Plugin installer will not install extension
platform: Any CPU

#branches:
#  only:
#    - master
#    - develop

before_build:
  - nuget restore

build:
  project: AlexPovar.ResharperTweaks.sln
  verbosity: minimal
  
after_build:
  - nuget pack AlexPovar.ResharperTweaks.nuspec -Version %APPVEYOR_BUILD_VERSION% -BasePath AlexPovar.ResharperTweaks\bin\Release
  #If I use artifacts section, name will contain relative path.
  - appveyor PushArtifact AlexPovar.ResharperTweaks\bin\Release\AlexPovar.ResharperTweaks.dll
  
test: off

artifacts:
  - path: '*.nupkg'
    
assembly_info:
  patch: true
  file: AlexPovar.ResharperTweaks\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'