environment:
  build_version: '1.0.0.{build}'
  #I should build AnyCPU instead of x86. Otherwise, Plugin installer will not install extension
  build_platform: Any CPU  

######## RELEASE CONFIGURATION ########
-
  branches:
   only:
     - feature/support-release-in-build-script
  
  version: {build_version}
  configuration: Release
  platform: {build_platform}

  before_build:
    - nuget restore

  build:
    project: AlexPovar.ResharperTweaks.sln
    verbosity: minimal
  
  after_build:
    - nuget pack AlexPovar.ResharperTweaks.nuspec -Version %APPVEYOR_BUILD_VERSION% -BasePath AlexPovar.ResharperTweaks\bin\Release
  
#  test:
#    assemblies:
#      - AlexPovar.ResharperTweaks.Tests.dll
  test: off

  artifacts:
    - path: '*.nupkg'
    
  assembly_info:
    patch: true
    file: AlexPovar.ResharperTweaks\Properties\AssemblyInfo.cs
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}-rc1'
    