######## RELEASE CONFIGURATION ########
-
  #Run builds for tags only
  branches:
    only:
      - master
      - /v\d(.\d)+/
      - /v\d(.\d)+-beta/
  
  skip_non_tags: true
  
  #Don't forget to update version for DEV build too
  version: 1.0.0.{build}
  configuration: Release
  platform: Any CPU
  
  environment:
    SEMANTIC_BUILD_VERSION: $(APPVEYOR_BUILD_VERSION)
    IS_PRERELASE_BUILD: false
    SKIP: true
  
  init:
    - ps: >
        Write-Host ">>>>>>>>> RUN RELEASE BUILD WITH DEPLOY <<<<<<<<<<<"
        
        $tagSuffix = [regex]::Match($env:APPVEYOR_REPO_TAG_NAME, "\d(.\d)+-(?<suffix>(\w)+)").Groups['suffix'].value
        
        if($tagSuffix) 
        { 
          $env:SEMANTIC_BUILD_VERSION = "$env:SEMANTIC_BUILD_VERSION-$tagSuffix"
          
          $env:IS_PRERELASE_BUILD = True
        }
        
        Write-Host "SEMANTIC VERSION: $env:SEMANTIC_BUILD_VERSION"
            
  before_build:
    - nuget restore

  build:
    project: AlexPovar.ReSharperHelpers.sln
    verbosity: minimal
  
  after_build:
    - nuget pack AlexPovar.ReSharperHelpers.nuspec -Version %APPVEYOR_BUILD_VERSION% -BasePath AlexPovar.ReSharperHelpers\bin\Release
  
  test:
    off
#    assemblies:
#      - AlexPovar.ReSharperHelpers.Tests.dll

  artifacts:
    - path: '*.nupkg'
    
  assembly_info:
    patch: true
    file: AlexPovar.ReSharperHelpers\Properties\AssemblyInfo.cs
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    
  deploy:
    -
      release: AlexPovar.ReSharperHelpers $(APPVEYOR_REPO_TAG_NAME)
      description: >
        ### Release notes:
          - XXX
      provider: GitHub
      auth_token:
        secure: OzVU+dQH6Xnhe6lBhEjUsJNTfKHQCT22+khHIBi2zRMelT+UzW1rCgGunZtAlBWP
      artifact: /.*\.nupkg/
      draft: true
      prerelease: false
      on:
        appveyor_repo_tag: true         # deploy on tag push only
        IS_PRERELASE_BUILD: false       # skip pre-release builds
        SKIP: false
    -
      provider: NuGet
      server: https://resharper-plugins.jetbrains.com
      api_key:
        secure: n7O2pQ5KhsdnT2DhKmiU40gCt3Tl3/T/zxnclsYxgYwgxpNK2iZvK9apawWFMpCO
      skip_symbols: true
      artifact: /.*\.nupkg/
      on:
        appveyor_repo_tag: true
        SKIP: false
      
######## LATEST BUILD ########
-
  version: 1.0.0.{build}
  configuration: Release
  platform: Any CPU
    
  init:
    - ps: Write-Host ">>>>>>>>> RUN LATEST BUILD <<<<<<<<<<<"
    
  before_build:
    - nuget restore
    
  build:
    project: AlexPovar.ReSharperHelpers.sln
    verbosity: minimal
    
  after_build:
    - nuget pack AlexPovar.ReSharperHelpers.nuspec -Version %APPVEYOR_BUILD_VERSION% -BasePath AlexPovar.ReSharperHelpers\bin\Release
    
  test: off
  
  artifacts:
    - path: '*.nupkg'
      name: LATEST package