image: Visual Studio 2017

environment:
  RESHARPER_GALLERY_KEY:
    secure: ZHMReQXlwdjhYK3JPKDy8zckH93IR0bvNW6vx1JrWtjciAPlbcttAhDJZhS0UV3DeJiG91Xk/ngBDflfJy3lXS8jGmCIiZ+EmkuWgrHwSeQ=
  MYGET_KEY:
    secure: 4p4wi7VlIH54Ue2IKX5E8FW30mZeHihIevL9l+nKol4w4UWRmIWbBhnGs1iflu4F

pull_requests:
  do_not_increment_build_number: true

build_script:
- ps: |
    & .\build.cmd AppVeyor NuGetPublicKey="$($Env:RESHARPER_GALLERY_KEY)" NuGetPrivateKey="$($Env:MYGET_KEY)" BuildVersion=git BuildNumber=$($Env:APPVEYOR_BUILD_NUMBER) 

test: off
deploy: off

artifacts:
  - path: 'build\NuGetPackages\*.nupkg'
