######## RELEASE CONFIGURATION ########
-
  #Run builds for tags only
  branches:
    only:
    - /v\d(.\d)+/
  
  skip_non_tags: true
  
  #Don't forget to update version for DEV build too
  version: 0.0.0.{build}
  configuration: Release
  platform: Any CPU
  
  init:
    - ps: Write-Host ">>>>>>>>> RUN RELEASE BUILD WITH DEPLOY <<<<<<<<<<<"

  before_build:
    - nuget restore

  build:
    project: AlexPovar.ResharperTweaks.sln
    verbosity: minimal
  
  after_build:
    - nuget pack AlexPovar.ResharperTweaks.nuspec -Version %APPVEYOR_BUILD_VERSION% -BasePath AlexPovar.ResharperTweaks\bin\Release
  
  test:
    assemblies:
      - AlexPovar.ResharperTweaks.Tests.dll

  artifacts:
    - path: '*.nupkg'
    
  assembly_info:
    patch: true
    file: AlexPovar.ResharperTweaks\Properties\AssemblyInfo.cs
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    
  deploy:
    -
      release: AlexPovar.ResharperTweaks $(APPVEYOR_REPO_TAG_NAME)
      description: >
        ### Release notes:
          - XXX
      provider: GitHub
      auth_token:
        secure: OzVU+dQH6Xnhe6lBhEjUsJNTfKHQCT22+khHIBi2zRMelT+UzW1rCgGunZtAlBWP
      artifact: /.*\.nupkg/
      draft: true
      prerelease: false
      on:
        appveyor_repo_tag: true        # deploy on tag push only   
    -
      provider: NuGet
      server: https://resharper-plugins.jetbrains.com
      api_key:
        secure: n7O2pQ5KhsdnT2DhKmiU40gCt3Tl3/T/zxnclsYxgYwgxpNK2iZvK9apawWFMpCO
      skip_symbols: true
      artifact: /.*\.nupkg/
      on:
        appveyor_repo_tag: true
      
######## DEBUG BUILD ########
-
  version: 0.0.0.{build}
  configuration: Debug
  platform: Any CPU
  
  init:
    - ps: Write-Host ">>>>>>>>> RUN DEBUG BUILD <<<<<<<<<<<"
  
  before_build:
    - nuget restore
    
  build:
    project: AlexPovar.ResharperTweaks.sln
    verbosity: minimal
    
  after_build:
    - nuget pack AlexPovar.ResharperTweaks.nuspec -Version %APPVEYOR_BUILD_VERSION% -BasePath AlexPovar.ResharperTweaks\bin\Debug
    
  test: off
  
  artifacts:
    - path: '*.nupkg'
      name: DEBUG build